### ISSUE TITLE
Fatal exception in version 1.8.0

### ISSUE THREAD

**Issue by jdefalco** [PubMatic/android-openwrap-sdk-samples#1]
After upgrading to version 1.8.0 I started seeing these fatal exceptions, apparently occurring when the SDK is loading an URL in a webview:

```
java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'PMSDKAudioChangeThread'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {30814c0} called on Looper (PMSDKAudioChangeThread, tid 69430) {5f8cf2a}, FYI main Looper is Looper (main, tid 2) {30814c0})
        at android.webkit.WebView.checkThread(WebView.java:2597)
        at android.webkit.WebView.loadUrl(WebView.java:732)
        at com.pubmatic.sdk.webrendering.mraid.n.k(Unknown:32)
        at com.pubmatic.sdk.webrendering.mraid.n.i(Unknown:52)
        at com.pubmatic.sdk.webrendering.mraid.r.w(Unknown:5)
        at com.pubmatic.sdk.webrendering.mraid.p.a(p)
        at com.pubmatic.sdk.webrendering.mraid.r$b.a(Unknown:17)
        at com.pubmatic.sdk.webrendering.mraid.e.b(Unknown:35)
        at com.pubmatic.sdk.webrendering.mraid.c.a(c)
        at com.pubmatic.sdk.webrendering.mraid.e$b.onChange(Unknown:23)
        at android.database.ContentObserver.onChange(ContentObserver.java:169)
        at android.database.ContentObserver.onChange(ContentObserver.java:187)
        at android.database.ContentObserver.onChange(ContentObserver.java:202)
        at android.database.ContentObserver.lambda$dispatchChange$0$ContentObserver(ContentObserver.java:282)
        at android.database.-$$Lambda$ContentObserver$MgqiYb2qvgLhoXTioYXq9MvvpNk.run(Unknown:10)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

```
Caused by: java.lang.Throwable: A WebView method was called on thread 'PMSDKAudioChangeThread'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {30814c0} called on Looper (PMSDKAudioChangeThread, tid 69430) {5f8cf2a}, FYI main Looper is Looper (main, tid 2) {30814c0})
        at android.webkit.WebView.checkThread(WebView.java:2592)
        at android.webkit.WebView.loadUrl(WebView.java:732)
        at com.pubmatic.sdk.webrendering.mraid.n.k(Unknown:32)
        at com.pubmatic.sdk.webrendering.mraid.n.i(Unknown:52)
        at com.pubmatic.sdk.webrendering.mraid.r.w(Unknown:5)
        at com.pubmatic.sdk.webrendering.mraid.p.a(p)
        at com.pubmatic.sdk.webrendering.mraid.r$b.a(Unknown:17)
        at com.pubmatic.sdk.webrendering.mraid.e.b(Unknown:35)
        at com.pubmatic.sdk.webrendering.mraid.c.a(c)
        at com.pubmatic.sdk.webrendering.mraid.e$b.onChange(Unknown:23)
        at android.database.ContentObserver.onChange(ContentObserver.java:169)
        at android.database.ContentObserver.onChange(ContentObserver.java:187)
        at android.database.ContentObserver.onChange(ContentObserver.java:202)
        at android.database.ContentObserver.lambda$dispatchChange$0$ContentObserver(ContentObserver.java:282)
        at android.database.-$$Lambda$ContentObserver$MgqiYb2qvgLhoXTioYXq9MvvpNk.run(Unknown:10)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by jdefalco** [comment]
Sorry, wrong project :)
