### ISSUE TITLE
IllegalStateException : com.pubmatic.sdk.nativead.renderer.POBNativeAdRenderer.a

### ISSUE THREAD

**Issue by kunalkhedkar** [PubMatic/android-openwrap-sdk-samples#3]
implementation 'com.pubmatic.sdk:openwrap:3.4.0

com.pubmatic.sdk.nativead.renderer.POBNativeAdRenderer.a
java.lang.IllegalStateException - The specified child already has a parent. You must call removeView() on the child's parent first.

Crashlytic logs
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5109)
       at android.view.ViewGroup.addView(ViewGroup.java:4938)
       at android.view.ViewGroup.addView(ViewGroup.java:4878)
       at android.view.ViewGroup.addView(ViewGroup.java:4851)
       at com.pubmatic.sdk.nativead.renderer.POBNativeAdRenderer.a(SourceFile:31)
       at com.pubmatic.sdk.nativead.renderer.POBNativeAdRenderer.onComplete(POBNativeAdRenderer.java:143)
       at com.pubmatic.sdk.common.utility.POBImageDownloadManager.a(POBImageDownloadManager.java:143)
       at com.pubmatic.sdk.common.utility.POBImageDownloadManager.b(POBImageDownloadManager.java:22)
       at com.pubmatic.sdk.common.utility.POBImageDownloadManager$a.onSuccess(POBImageDownloadManager.java:22)
       at com.pubmatic.sdk.common.network.POBNetworkHandler$d.a(SourceFile:7)
       at com.pubmatic.sdk.common.network.POBNetworkHandler$d.onResponse(SourceFile:7)
       at com.android.volley.toolbox.ImageRequest.deliverResponse(ImageRequest.java:257)
       at com.android.volley.toolbox.ImageRequest.deliverResponse(ImageRequest.java:34)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7604)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

**Comment by vishal-patil298** [comment]
Hi @kunalkhedkar, Thanks for reaching out to us! We have looked into the issue and fixed it; it will be added to the upcoming OpenWrap SDK releases and will share the release version here.

Meanwhile, to unblock this use case, we recommend that for custom Standard NativeAd, while passing the instance of **POBNativeTemplateView**, make sure that it does not have a parent.

You can also refer:  https://help.pubmatic.com/openwrap/docs/show-native-ads#using-custom-layout for rendering custom standard native ad.

**Comment by pm-vishal-chougule** [comment]
Closing the issue as it has been fixed in OpenWrap SDK v3.6.0.
